name: Build and Deploy Python App to Azure

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'


      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Login to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PratikAImodel'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.'

